apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollamac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollamac
  template:
    metadata:
      labels:
        app: ollamac
    spec:
      containers:
      - name: ollamac
        image: ollama/ollama
        ports:
        - containerPort: 11434
        # env:
        # - name: OLLAMA_MODELS
        #   value: "/Models"
        resources:
          limits:
            cpu: "2"
            memory: "2048Mi"
      #   volumeMounts:
      #   - name: models-volume
      #     mountPath: /root/.ollama/models
      #   - name: ollama-volume
      #     mountPath: /root/.ollama
      # volumes:
      # - name: models-volume
      #   hostPath:
      #     path: "D:\\Programs\\Ollama\\models"
      # - name: ollama-volume
      #   persistentVolumeClaim:
      #     claimName: ollama-pvc
        volumeMounts:
        - name: models-volume
          mountPath: /root/.ollama/models
      volumes:
      - name: models-volume
        hostPath:
          path: "/mnt/models"

---
apiVersion: v1
kind: Service
metadata:
  name: ollamac
spec:
  selector:
    app: ollamac
  ports:
  - protocol: TCP
    port: 11434
    targetPort: 11434
  type: NodePort
